#!/usr/bin/python

import web
import os
import time

# 获取配置中的数据库密码
pwd = os.popen('cat /usr/local/amengcdn/conf/amengcdn.conf | grep DB_PassWord | awk -F= \'{print $2}\'').read()
db = web.database(dbn = 'mysql',
                    db='cdn_info',
                    user='root',
                    pw=pwd[:-1],
                    host='hls.mydomain.com',
                    port=3306,
                )
print 'Database connected.'
while True:
    rs = db.select('node_info', what = 'NodeIP')
    for r in rs:
        cmd = 'ping -W 3 -c 2 %s' % r.NodeIP
        result = os.popen(cmd).read()
        if result.find('time=') != -1:
            print '\033[92m'+r.NodeIP+' is up'+'\033[0m'
            db.update('node_info', status = 'on', where = 'NodeIP = $NodeIP', vars = r)
        else:
            print '\033[91m' + r.NodeIP + ' is down.' + '\033[0m'
            db.update('node_info', status='off', where='NodeIP = $NodeIP', vars=r)

    time.sleep(5)


